name: Questioner
main: ca.xshade.bukkit.questioner.Questioner
version: 0.1
author: Shade
website: http://towny.xshade.ca
description: Ask questions to players. Including polling.
commands:
    q:
        description: Master command for questions.